const nameDict: {[x: string]: string} = {
    // polaris
    akagi_mu: "Ootori_Shikikan",
    hipper_mu: "R-Guitarist",
    gascogne_mu: "GascogneT8",
    sheffield_mu: "ShiningS",
    commander: "commander__",
    cleveland_mu: "Cleveland☆Knight",
    columbia: "Cleve-FC.3",
    montpelier: "Cleve-FC.1",
    denver: "Cleve-FC.2",
    kaga: "Ran_mew",
    eugen: "P.Eugen",
    spee: "GRAFSPEE",
    deutschland: "SPEE_FIGHT",
    shoukaku: "KADEKURU",
    zuikaku: "Zuikaku",
    belfast: "Belfast_inService",

    // 20설날
    suruga: "S8u6r6ug8A",
    kongo: "BarrowYoko",
    kasumi: "fuwarin1118",
    nagato: "SakuraCombinedFleet",
    ark_royal: "ArkRoyal_Defense",
    ayanami: "AYANAMIN",
    hibiki: "HibikiChannel",
    inazuma: "DEN",
    ikazuchi: "RAI",
    akatsuki: "NINJA-AKATSUKI",
    fubuki: "bukkitoku1",
    noshiro: "Nshiro",
    agano: "FinalOTU",
    kirishima: "KirinnKS",
    ryuhou: "PhoenixWhale",
    yubari: "Kagakubu.org",
    unicorn: "UnicornI72",
    z23: "Zerstörer.23",
    friedrich: "SymphonicStigma",
    atago: "Atago",
    azuma: "AzumaB65",
    dunkerque: "gateaumistress",
    trento: "Da Trento",
    i58: "I58_sensuisenntai",
    i26: "I26_sensuisenntai",
    i25: "I25_sensuisenntai",
    shoho: "SHOHO",
    z35: "funf&#9825;3536",
    z36: "Zech3536",
    saratoga: "SisterSara",
    shiranui: "KoubaiStaff_unofficial",
    myoko: "Myoko_CA",
    kinu: "RageofONI",
    isuzu: "Isuzuzu",
    nagara: "Nagara_CA",
    abukuma: "AbuAbu",
    birmingham: "Cleve-FC.4",
    edinburgh: "☆ Royal Maid ☆",
    southampton: "MINAMIpton",
    glorius: "Glorius"

    //
};

const getAccount = (name: string) => nameDict[name] ?? '-';

export {
    nameDict,
    getAccount,
}